/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.records;

import edu.java.domain.jooq.tables.GithubLinks;
import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class GithubLinksRecord extends UpdatableRecordImpl<GithubLinksRecord>
    implements Record4<Long, OffsetDateTime, OffsetDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GITHUB_LINKS.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>GITHUB_LINKS.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>GITHUB_LINKS.LAST_UPDATE</code>.
     */
    public void setLastUpdate(@Nullable OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>GITHUB_LINKS.LAST_UPDATE</code>.
     */
    @Nullable
    public OffsetDateTime getLastUpdate() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>GITHUB_LINKS.LAST_PUSH</code>.
     */
    public void setLastPush(@Nullable OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>GITHUB_LINKS.LAST_PUSH</code>.
     */
    @Nullable
    public OffsetDateTime getLastPush() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>GITHUB_LINKS.PULL_REQUESTS_COUNT</code>.
     */
    public void setPullRequestsCount(@Nullable Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>GITHUB_LINKS.PULL_REQUESTS_COUNT</code>.
     */
    @Nullable
    public Integer getPullRequestsCount() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Long, OffsetDateTime, OffsetDateTime, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row4<Long, OffsetDateTime, OffsetDateTime, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return GithubLinks.GITHUB_LINKS.LINK_ID;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field2() {
        return GithubLinks.GITHUB_LINKS.LAST_UPDATE;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field3() {
        return GithubLinks.GITHUB_LINKS.LAST_PUSH;
    }

    @Override
    @NotNull
    public Field<Integer> field4() {
        return GithubLinks.GITHUB_LINKS.PULL_REQUESTS_COUNT;
    }

    @Override
    @NotNull
    public Long component1() {
        return getLinkId();
    }

    @Override
    @Nullable
    public OffsetDateTime component2() {
        return getLastUpdate();
    }

    @Override
    @Nullable
    public OffsetDateTime component3() {
        return getLastPush();
    }

    @Override
    @Nullable
    public Integer component4() {
        return getPullRequestsCount();
    }

    @Override
    @NotNull
    public Long value1() {
        return getLinkId();
    }

    @Override
    @Nullable
    public OffsetDateTime value2() {
        return getLastUpdate();
    }

    @Override
    @Nullable
    public OffsetDateTime value3() {
        return getLastPush();
    }

    @Override
    @Nullable
    public Integer value4() {
        return getPullRequestsCount();
    }

    @Override
    @NotNull
    public GithubLinksRecord value1(@NotNull Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public GithubLinksRecord value2(@Nullable OffsetDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    @NotNull
    public GithubLinksRecord value3(@Nullable OffsetDateTime value) {
        setLastPush(value);
        return this;
    }

    @Override
    @NotNull
    public GithubLinksRecord value4(@Nullable Integer value) {
        setPullRequestsCount(value);
        return this;
    }

    @Override
    @NotNull
    public GithubLinksRecord values(
        @NotNull Long value1,
        @Nullable OffsetDateTime value2,
        @Nullable OffsetDateTime value3,
        @Nullable Integer value4
    ) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GithubLinksRecord
     */
    public GithubLinksRecord() {
        super(GithubLinks.GITHUB_LINKS);
    }

    /**
     * Create a detached, initialised GithubLinksRecord
     */
    @ConstructorProperties({"linkId", "lastUpdate", "lastPush", "pullRequestsCount"})
    public GithubLinksRecord(
        @NotNull Long linkId,
        @Nullable OffsetDateTime lastUpdate,
        @Nullable OffsetDateTime lastPush,
        @Nullable Integer pullRequestsCount
    ) {
        super(GithubLinks.GITHUB_LINKS);

        setLinkId(linkId);
        setLastUpdate(lastUpdate);
        setLastPush(lastPush);
        setPullRequestsCount(pullRequestsCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GithubLinksRecord
     */
    public GithubLinksRecord(edu.java.domain.jooq.tables.pojos.GithubLinks value) {
        super(GithubLinks.GITHUB_LINKS);

        if (value != null) {
            setLinkId(value.getLinkId());
            setLastUpdate(value.getLastUpdate());
            setLastPush(value.getLastPush());
            setPullRequestsCount(value.getPullRequestsCount());
            resetChangedOnNotNull();
        }
    }
}
