/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables;

import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.tables.records.UserTrackedLinksRecord;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class UserTrackedLinks extends TableImpl<UserTrackedLinksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>USER_TRACKED_LINKS</code>
     */
    public static final UserTrackedLinks USER_TRACKED_LINKS = new UserTrackedLinks();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<UserTrackedLinksRecord> getRecordType() {
        return UserTrackedLinksRecord.class;
    }

    /**
     * The column <code>USER_TRACKED_LINKS.USER_ID</code>.
     */
    public final TableField<UserTrackedLinksRecord, Long> USER_ID =
        createField(DSL.name("USER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>USER_TRACKED_LINKS.LINK_ID</code>.
     */
    public final TableField<UserTrackedLinksRecord, Long> LINK_ID =
        createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private UserTrackedLinks(Name alias, Table<UserTrackedLinksRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserTrackedLinks(Name alias, Table<UserTrackedLinksRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>USER_TRACKED_LINKS</code> table reference
     */
    public UserTrackedLinks(String alias) {
        this(DSL.name(alias), USER_TRACKED_LINKS);
    }

    /**
     * Create an aliased <code>USER_TRACKED_LINKS</code> table reference
     */
    public UserTrackedLinks(Name alias) {
        this(alias, USER_TRACKED_LINKS);
    }

    /**
     * Create a <code>USER_TRACKED_LINKS</code> table reference
     */
    public UserTrackedLinks() {
        this(DSL.name("USER_TRACKED_LINKS"), null);
    }

    public <O extends Record> UserTrackedLinks(Table<O> child, ForeignKey<O, UserTrackedLinksRecord> key) {
        super(child, key, USER_TRACKED_LINKS);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<UserTrackedLinksRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_6BE;
    }

    @Override
    @NotNull
    public List<ForeignKey<UserTrackedLinksRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_6, Keys.CONSTRAINT_6B);
    }

    private transient Users _users;
    private transient Links _links;

    /**
     * Get the implicit join path to the <code>PUBLIC.USERS</code> table.
     */
    public Users users() {
        if (_users == null) {
            _users = new Users(this, Keys.CONSTRAINT_6);
        }

        return _users;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINKS</code> table.
     */
    public Links links() {
        if (_links == null) {
            _links = new Links(this, Keys.CONSTRAINT_6B);
        }

        return _links;
    }

    @Override
    @NotNull
    public UserTrackedLinks as(String alias) {
        return new UserTrackedLinks(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public UserTrackedLinks as(Name alias) {
        return new UserTrackedLinks(alias, this);
    }

    @Override
    @NotNull
    public UserTrackedLinks as(Table<?> alias) {
        return new UserTrackedLinks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public UserTrackedLinks rename(String name) {
        return new UserTrackedLinks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public UserTrackedLinks rename(Name name) {
        return new UserTrackedLinks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public UserTrackedLinks rename(Table<?> name) {
        return new UserTrackedLinks(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
