/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StackoverflowLinks implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long linkId;
    private OffsetDateTime lastUpdate;
    private Integer answersCount;

    public StackoverflowLinks() {
    }

    public StackoverflowLinks(StackoverflowLinks value) {
        this.linkId = value.linkId;
        this.lastUpdate = value.lastUpdate;
        this.answersCount = value.answersCount;
    }

    @ConstructorProperties({"linkId", "lastUpdate", "answersCount"})
    public StackoverflowLinks(
        @NotNull Long linkId,
        @Nullable OffsetDateTime lastUpdate,
        @Nullable Integer answersCount
    ) {
        this.linkId = linkId;
        this.lastUpdate = lastUpdate;
        this.answersCount = answersCount;
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINKS.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINKS.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINKS.LAST_UPDATE</code>.
     */
    @Nullable
    public OffsetDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINKS.LAST_UPDATE</code>.
     */
    public void setLastUpdate(@Nullable OffsetDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINKS.ANSWERS_COUNT</code>.
     */
    @Nullable
    public Integer getAnswersCount() {
        return this.answersCount;
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINKS.ANSWERS_COUNT</code>.
     */
    public void setAnswersCount(@Nullable Integer answersCount) {
        this.answersCount = answersCount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final StackoverflowLinks other = (StackoverflowLinks) obj;
        if (this.linkId == null) {
            if (other.linkId != null) {
                return false;
            }
        } else if (!this.linkId.equals(other.linkId)) {
            return false;
        }
        if (this.lastUpdate == null) {
            if (other.lastUpdate != null) {
                return false;
            }
        } else if (!this.lastUpdate.equals(other.lastUpdate)) {
            return false;
        }
        if (this.answersCount == null) {
            if (other.answersCount != null) {
                return false;
            }
        } else if (!this.answersCount.equals(other.answersCount)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.lastUpdate == null) ? 0 : this.lastUpdate.hashCode());
        result = prime * result + ((this.answersCount == null) ? 0 : this.answersCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StackoverflowLinks (");

        sb.append(linkId);
        sb.append(", ").append(lastUpdate);
        sb.append(", ").append(answersCount);

        sb.append(")");
        return sb.toString();
    }
}
